# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Exact beta-binomial density using a multiprecision library.
#'
#' \code{dBetaBinom_MP} calculates the beta-binomial density while
#' avoiding numerical mistakes (catastrophic cancellations) due to 
#' extreme parameter values. This function is called by \code{dBetaBinom}
#' if necessary, and should not be called outside of this.
#'
#' @param ms Numeric vector. Vector of number of successes
#' @param ns Numeric vector. Vector of number of trials
#' @param piX Number. Probability of success; \code{0 >= piX >= 1}
#' @param thetaX Number. Dispersion parameter; \code{0 >= thetaX > +Inf}
#' @param LOG Logical. if TRUE, return log-densities
#' @param NecPres Number. Necessary Precision, i.e. number of bits, for an accurate density calculatation, as determined by the function \code{dBetaBinom}
#' @return A numeric vector of the same length as ms and ns, containing (log-)beta-binomial densities
#' @export
dBetaBinom_MP <- function(ms, ns, piX, thetaX, LOG, NecPres) {
    .Call(`_MAGE_dBetaBinom_MP`, ms, ns, piX, thetaX, LOG, NecPres)
}

#' Exact gradient of the beta-binomial log-likelihood function for pi using a multiprecision library.
#'
#' \code{grad_pi_MP} calculates the value of the gradient of the beta-binomial log-likelihood function to pi
#' at given data points, while avoiding numerical mistakes (catastrophic cancellations) due to 
#' extreme parameter values. This function is called by \code{grad_pi}
#' if necessary, and should not be called outside of this.
#'
#' @param ms Numeric vector. Vector of number of successes
#' @param ns Numeric vector. Vector of number of trials
#' @param piX Number. Probability of success; \code{0 >= piX >= 1}
#' @param thetaX Number. Dispersion parameter; \code{0 >= thetaX > +Inf}
#' @param NecPres Number. Necessary Precision, i.e. number of bits, for an accurate gradient calculatation, as determined by the function \code{grad_pi}
#' @return A numeric vector of the same length as ms and ns, containing the gradient to pi in the give data points
#' @export
grad_pi_MP <- function(ms, ns, piX, thetaX, NecPres) {
    .Call(`_MAGE_grad_pi_MP`, ms, ns, piX, thetaX, NecPres)
}

#' Exact gradient of the beta-binomial log-likelihood function for theta using a multiprecision library.
#'
#' \code{grad_theta_MP} calculates the value of the gradient of the beta-binomial log-likelihood function to theta
#' at given data points, while avoiding numerical mistakes (catastrophic cancellations) due to 
#' extreme parameter values. This function is called by \code{grad_theta}
#' if necessary, and should not be called outside of this.
#'
#' @param ms Numeric vector. Vector of number of successes
#' @param ns Numeric vector. Vector of number of trials
#' @param piX Number. Probability of success; \code{0 >= piX >= 1}
#' @param thetaX Number. Dispersion parameter; \code{0 >= thetaX > +Inf}
#' @param NecPres Number. Necessary Precision, i.e. number of bits, for an accurate gradient calculatation, as determined by the function \code{grad_pi}
#' @return A numeric vector of the same length as ms and ns, containing the gradient to theta in the give data points
#' @export
grad_theta_MP <- function(ms, ns, piX, thetaX, NecPres) {
    .Call(`_MAGE_grad_theta_MP`, ms, ns, piX, thetaX, NecPres)
}

#' Exact beta-binomial density using sums.
#'
#' \code{dBetaBinom_cpp_old} calculates the beta-binomial density via
#' a number of sums, which is slow for high-value data
#' but fast for low-value data.
#' This function is called by \code{dBetaBinom}
#' if necessary, and should not be called outside of this.
#'
#' @param ms Numeric vector. Vector of number of successes
#' @param ns Numeric vector. Vector of number of trials
#' @param pi Number. Probability of success; \code{0 >= pi >= 1}
#' @param theta Number. Dispersion parameter; \code{0 >= theta > +Inf}
#' @param LOG Logical. if TRUE, return log-densities
#' @return A numeric vector of the same length as ms and ns, containing (log-)beta-binomial densities
#' @export
dBetaBinom_cpp_old <- function(ms, ns, pi, theta, LOG) {
    .Call(`_MAGE_dBetaBinom_cpp_old`, ms, ns, pi, theta, LOG)
}

#' Exact gradient of the beta-binomial log-likelihood function for pi using sums.
#'
#' \code{grad_pi_old} calculates the value of the gradient of the beta-binomial log-likelihood function to pi
#' at given data points via a number of sums, which is slow for high-value data
#' but fast for low-value data.
#' This function is called by \code{grad_pi} if necessary, and should not be called outside of this.
#'
#' @param ms Numeric vector. Vector of number of successes
#' @param ns Numeric vector. Vector of number of trials
#' @param pi Number. Probability of success; \code{0 >= pi >= 1}
#' @param theta Number. Dispersion parameter; \code{0 >= theta > +Inf}
#' @return A numeric vector of the same length as ms and ns, containing the gradient to pi in the give data points
#' @export
grad_pi_old <- function(ms, ns, pi, theta) {
    .Call(`_MAGE_grad_pi_old`, ms, ns, pi, theta)
}

#' Exact gradient of the beta-binomial log-likelihood function for theta using sums.
#'
#' \code{grad_theta_old} calculates the value of the gradient of the beta-binomial log-likelihood function to theta
#' at given data points via a number of sums, which is slow for high-value data
#' but fast for low-value data.
#' This function is called by \code{grad_theta}
#' if necessary, and should not be called outside of this.
#'
#' @param ms Numeric vector. Vector of number of successes
#' @param ns Numeric vector. Vector of number of trials
#' @param pi Number. Probability of success; \code{0 >= pi >= 1}
#' @param theta Number. Dispersion parameter; \code{0 >= theta > +Inf}
#' @return A numeric vector of the same length as ms and ns, containing the gradient to theta in the give data points
#' @export
grad_theta_old <- function(ms, ns, pi, theta) {
    .Call(`_MAGE_grad_theta_old`, ms, ns, pi, theta)
}

